export type Employee = {
    id: null | number;
    profile_picture: null | string;
    emp_code: string;
    first_name: string;
    last_name: string;
    description: string;
    email: string;
    phone: string;
    password: string;
    position: string;
    organizational_unit: string;
    report_to: null | number;
    language: string;
    is_active: boolean;
    is_project_leader: boolean;
    is_project_approver: boolean;
    is_project_member: boolean;
    created_by: null | number;
    created_datetime: null | string;
    updated_by: null | number;
    updated_datetime: null | string;
};

export type Permission = {
    id: null | number;
    md_policy_view: boolean;
    kpi_alignment_view: boolean;
    project_view: boolean;
    project_create: boolean;
    project_update: boolean;
    project_delete: boolean;
    report_view: boolean;
    report_update: boolean;
    report_delete: boolean;
    dashboard_executive_view: boolean;
    dashboard_manager_view: boolean;
    dashboard_user_view: boolean;
    admin_view: boolean;
    cost_saving_type_view: boolean;
    cost_saving_type_create: boolean;
    cost_saving_type_update: boolean;
    cost_saving_type_delete: boolean;
    policy_view: boolean;
    policy_create: boolean;
    policy_update: boolean;
    policy_delete: boolean;
    kpi_view: boolean;
    kpi_create: boolean;
    kpi_update: boolean;
    kpi_delete: boolean;
    organizational_unit_view: boolean;
    organizational_unit_create: boolean;
    organizational_unit_update: boolean;
    organizational_unit_delete: boolean;
    employee_view: boolean;
    employee_create: boolean;
    employee_update: boolean;
    employee_delete: boolean
    permission_for: null | number;
}